
### Server health check
GET http://localhost:5000/health
Content-Type: application/json

### craate a new user
POST http://localhost:5000/api/users
Content-Type: application/json

{
  "userId": 2,
  "username": "Rayhan234",
  "password": "Bangladesh",
  "fullName": {
    "firstName": "Rayhan",
    "lastName": "Mojumdar"
  },
  "age": 25,
  "email": "john@example.com",
  "isActive": true,
  "hobbies": ["reading", "gardening"],
  "address": {
    "street": "123 Main Street",
    "city": "Example City",
    "country": "Example Country"
  }
}